version: "3.9"

services:
  backend:
    build: ./server/WeChat        
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/ChatMe
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - CENTRIFUGO_API_URL=http://centrifugo:8000

    restart: unless-stopped

  frontend:
    build: ./client/chatme
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./client/chatme:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: ["npm", "start"]

  centrifugo:
    image: centrifugo/centrifugo-pro:v6.4.0
    container_name: centrifugo
    command: ["centrifugo", "-c", "/centrifugo/config.json"]
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json:ro
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:8.0-M03-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    restart: unless-stopped

volumes:
  cache:
    driver: local
